// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVlUsR5I431yfG2M6SkMygIbyQte2ouDk',
    appId: '1:477774202426:web:0514b370ea7805eb751703',
    messagingSenderId: '477774202426',
    projectId: 'expense-tracker-bb8f3',
    authDomain: 'expense-tracker-bb8f3.firebaseapp.com',
    storageBucket: 'expense-tracker-bb8f3.firebasestorage.app',
    measurementId: 'G-D9ZY48MDFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvsEVxxJqk_yijaB-jHJYAH99UYVABLI',
    appId: '1:477774202426:android:9cbb696be24ea055751703',
    messagingSenderId: '477774202426',
    projectId: 'expense-tracker-bb8f3',
    storageBucket: 'expense-tracker-bb8f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3wwl4Ak2s0FZSIFGJDkhUVpiiZ-kstDI',
    appId: '1:477774202426:ios:410a97782ec7a8ac751703',
    messagingSenderId: '477774202426',
    projectId: 'expense-tracker-bb8f3',
    storageBucket: 'expense-tracker-bb8f3.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3wwl4Ak2s0FZSIFGJDkhUVpiiZ-kstDI',
    appId: '1:477774202426:ios:410a97782ec7a8ac751703',
    messagingSenderId: '477774202426',
    projectId: 'expense-tracker-bb8f3',
    storageBucket: 'expense-tracker-bb8f3.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVlUsR5I431yfG2M6SkMygIbyQte2ouDk',
    appId: '1:477774202426:web:01f6ce4daf5b4d1d751703',
    messagingSenderId: '477774202426',
    projectId: 'expense-tracker-bb8f3',
    authDomain: 'expense-tracker-bb8f3.firebaseapp.com',
    storageBucket: 'expense-tracker-bb8f3.firebasestorage.app',
    measurementId: 'G-6R7MWERWLV',
  );
}
